### ISSUE TITLE
tensorflow for cpu installed but not working (windows 10 and python 3.6.8)

### ISSUE THREAD

**Issue by BrunoCapron** [BrunoCapron/Process-Control-with-Machine-Learning#1]
The installation of tensorflow using the `pip install tensorflow` command was successful but when I test the command `import tensorflow as tf` with `cmd.exe`, I get the following result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Bruno\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'tensorflow.python'
```
I am using `python 3.6.8` and windows 10. Can someone please suggest some solutions?

**Comment by BrunoCapron** [comment]
I finally managed to install tensorflow following https://www.youtube.com/watch?v=jaSD7Lfp_7M.
